In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df = pd.read_pickle('./utseus-poi-dianping.pk')

In [3]:
type(df)

geopandas.geodataframe.GeoDataFrame

In [4]:
df.head()

,name,branch_name,address,telephone,city,avg_rating,product_grade,decoration_grade,service_grade,product_score,decoration_score,service_score,review_count,avg_price,photo_count,category,latitude,longitude,geometry
business_id,,,,,,,,,,,,,,,,,,,
500000,阿凡提美食娱乐城(这是一条测试商户数据，仅用于测试开发，开发完成后请申请正式数据...),,虹口区曲阳路775号天山宾馆B1楼,021-65559604,上海,30.0,1.0,1.0,1.0,6.8,6.3,6.3,482,81.0,140.0,新疆菜,31.290270,121.485969,POINT (121.4859694378507 31.29027007137677)
500001,萨莎(这是一条测试商户数据，仅用于测试开发，开发完成后请申请正式数据...),,徐汇区东平路11号,021-64746628,上海,40.0,1.0,1.0,1.0,7.3,8.4,7.4,891,149.0,441.0,酒吧,31.210445,121.445120,POINT (121.4451198540866 31.21044487104275)
500001,萨莎(这是一条测试商户数据，仅用于测试开发，开发完成后请申请正式数据...),,徐汇区东平路11号,021-64746628,上海,40.0,1.0,1.0,1.0,7.3,8.4,7.4,891,149.0,441.0,牛排,31.210445,121.445120,POINT (121.4451198540866 31.21044487104275)
500003,1221餐馆(这是一条测试商户数据，仅用于测试开发，开发完成后请申请正式数据...),,长宁区延安西路1221号,021-62136585,上海,35.0,1.0,1.0,1.0,7.1,7.4,7.6,369,144.0,182.0,本帮菜,31.213174,121.423148,POINT (121.4231477606538 31.21317357030482)
500008,Food Live(这是一条测试商户数据，仅用于测试开发，开发完成后请申请正式数据...),,浦东新区世纪大道88号金茂君悦大酒店B1楼,021-50491234-8283,上海,30.0,1.0,1.0,1.0,6.1,6.3,6.3,38,26.0,12.0,快餐简餐,31.237286,121.501334,POINT (121.501334104979 31.23728587667836)